name: Start Jobs

on: push

jobs:
  Build:
    uses: ./.github/workflows/build.yml

  UnitTests:
    uses: ./.github/workflows/test.yml

  Android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew :androidApp:assemble
